import { createItemFromDef } from '../inventory/ItemDefs.js';
import { validateConnectivity } from './MapConnectivityValidator.js';
import { MapBuilder } from './MapBuilder.js';
import { RoadGenerator } from './generators/RoadGenerator.js';
import { SplitRoadGenerator } from './generators/SplitRoadGenerator.js';
import { WindingRoadGenerator } from './generators/WindingRoadGenerator.js';
import { MirroredWindingRoadGenerator } from './generators/MirroredWindingRoadGenerator.js';
import { LabMapGenerator } from './generators/LabMapGenerator.js';
import { StartingRoadGenerator } from './generators/StartingRoadGenerator.js';
import { BranchingRoadGenerator } from './generators/BranchingRoadGenerator.js';
import { isSpecialBuilding } from './BuildingTypes.js';
import { isInsideCompound } from './MapUtils.js';
import { TEMPLATE_METADATA } from '../config/TemplateConfig.js';
import { MAP_GEN_CONFIG } from '../config/MapGenConfig.js';

import { gameRandom } from '../utils/SeededRandom.js';
/**
 * TemplateMapGenerator - Template-based map generation system
 * Generates maps from predefined templates with configurable parameters
 * Follows UniversalGoals.md: modular, testable, serializable
 */
export class TemplateMapGenerator {
  constructor() {
    this.templates = new Map();
    this.generators = new Map();
    this.loadDefaultTemplates();
    this.registerGenerators();
  }

  /**
   * Register template generators
   */
  registerGenerators() {
    this.generators.set('road', new RoadGenerator());
    this.generators.set('split_road', new SplitRoadGenerator());
    this.generators.set('winding_road', new WindingRoadGenerator());
    this.generators.set('mirrored_winding_road', new MirroredWindingRoadGenerator());
    this.generators.set('lab', new LabMapGenerator());
    this.generators.set('starting_road', new StartingRoadGenerator());
    this.generators.set('branching_road', new BranchingRoadGenerator());
  }

  /**
   * Load predefined map templates
   */
  loadDefaultTemplates() {
    // Small building template
    this.templates.set('small_building', {
      name: 'Small Building',
      size: { width: 10, height: 8 },
      layout: [
        'wwwwwwwwww',
        'w........w',
        'w..ff....w',
        'w..ff....w',
        'w........w',
        'w....ff..w',
        'w....ff..w',
        'wwwwwwwwww'
      ],
      spawnZones: {
        entrance: [{ x: 5, y: 7 }],
        center: [{ x: 4, y: 3 }, { x: 5, y: 4 }],
        corners: [{ x: 1, y: 1 }, { x: 8, y: 1 }, { x: 1, y: 6 }, { x: 8, y: 6 }]
      },
      parameters: {
        randomWalls: { min: 0, max: 3 },
        extraFloors: { min: 0, max: 5 }
      }
    });

    // Mall section template
    this.templates.set('mall_section', {
      name: 'Mall Section',
      size: { width: 15, height: 12 },
      layout: [
        'wwwwwwwwwwwwwww',
        'w.............w',
        'w.ff.......ff.w',
        'w.ff.......ff.w',
        'w.............w',
        'w.....fff.....w',
        'w.....fff.....w',
        'w.....fff.....w',
        'w.............w',
        'w.ff.......ff.w',
        'w.ff.......ff.w',
        'wwwwwwwwwwwwwww'
      ],
      spawnZones: {
        entrance: [{ x: 7, y: 11 }, { x: 1, y: 6 }, { x: 13, y: 6 }],
        center: [{ x: 7, y: 6 }, { x: 7, y: 7 }],
        shops: [
          { x: 2, y: 2 }, { x: 3, y: 2 }, { x: 12, y: 2 }, { x: 13, y: 2 },
          { x: 2, y: 9 }, { x: 3, y: 9 }, { x: 12, y: 9 }, { x: 13, y: 9 }
        ]
      },
      parameters: {
        randomWalls: { min: 1, max: 5 },
        extraFloors: { min: 2, max: 8 },
        shopVariations: ['small', 'medium', 'large']
      }
    });

    // Outdoor area template
    this.templates.set('outdoor_area', {
      name: 'Outdoor Area',
      size: { width: 20, height: 20 },
      layout: [
        'gggggggggggggggggggg',
        'gwwwwwwwwwwwwwwwwwwg',
        'gw................wg',
        'gw.ff............fwg',
        'gw.ff............fwg',
        'gw................wg',
        'gw......ffff......wg',
        'gw......ffff......wg',
        'gw......ffff......wg',
        'gw......ffff......wg',
        'gw................wg',
        'gw................wg',
        'gw......wwww......wg',
        'gw......w..w......wg',
        'gw......w..w......wg',
        'gw......wwww......wg',
        'gw................wg',
        'gw.ff............fwg',
        'gw.ff............fwg',
        'gwwwwwwwwwwwwwwwwwwg'
      ],
      spawnZones: {
        entrance: [{ x: 10, y: 19 }, { x: 1, y: 10 }, { x: 18, y: 10 }],
        building: [{ x: 13, y: 13 }, { x: 13, y: 14 }],
        openArea: [
          { x: 5, y: 5 }, { x: 15, y: 5 }, { x: 5, y: 15 }, { x: 15, y: 15 }
        ]
      },
      parameters: {
        randomWalls: { min: 2, max: 8 },
        extraFloors: { min: 3, max: 10 },
        buildingVariations: ['small', 'medium']
      }
    });

    // Road template - 45x125 map, procedurally generated by RoadGenerator.
    // No literal layout: the generator builds the full-size map. (The old hand-drawn
    // 20x39 strip was dead data that contradicted the declared 45x125 size.)
    this.templates.set('road', {
      name: TEMPLATE_METADATA.road.name,
      size: TEMPLATE_METADATA.road.size,
      layout: [], // Procedurally generated by RoadGenerator
      spawnZones: {
        roadStart: [{ x: TEMPLATE_METADATA.road.southEntranceX, y: TEMPLATE_METADATA.road.size.height - 2 }],
        roadEnd: [{ x: TEMPLATE_METADATA.road.northExitX, y: 1 }],
        roadside: [
          { x: 6, y: 15 }, { x: 13, y: 15 }, { x: 6, y: 20 }, { x: 13, y: 20 },
          { x: 6, y: 25 }, { x: 13, y: 25 }
        ]
      },
      parameters: {
        randomWalls: { min: 0, max: 2 },
        extraFloors: { min: 0, max: 3 }
      }
    });

    // Winding Road template - 75x125 map for S-curve suburban layout
    this.templates.set('winding_road', {
      name: TEMPLATE_METADATA.winding_road.name,
      size: TEMPLATE_METADATA.winding_road.size,
      layout: [], // Procedurally generated
      parameters: {
        randomWalls: { min: 0, max: 2 },
        extraFloors: { min: 0, max: 3 },
        roadThickness: 5,
        sidewalkThickness: 1
      }
    });

    // Mirrored Winding Road template
    this.templates.set('mirrored_winding_road', {
      name: TEMPLATE_METADATA.mirrored_winding_road.name,
      size: TEMPLATE_METADATA.mirrored_winding_road.size,
      layout: [], // Procedurally generated
      parameters: {
        randomWalls: { min: 0, max: 2 },
        extraFloors: { min: 0, max: 3 },
        roadThickness: 5,
        sidewalkThickness: 1
      }
    });

    // Split Road template
    this.templates.set('split_road', {
      name: TEMPLATE_METADATA.split_road.name,
      size: TEMPLATE_METADATA.split_road.size,
      layout: [], // Procedurally generated
      parameters: {
        randomWalls: { min: 0, max: 2 },
        extraFloors: { min: 0, max: 3 },
        roadThickness: 5,
        sidewalkThickness: 1
      }
    });

    // Lab template
    this.templates.set('lab', {
      name: TEMPLATE_METADATA.lab.name,
      size: TEMPLATE_METADATA.lab.size,
      layout: [], // Procedurally generated
      parameters: {}
    });

    // Branching Road template - wide central spine with procedural side-streets.
    // Sized at ~2x the winding-road maps (85x125) so side roads and building
    // blocks have real room to spread out from the central spine.
    this.templates.set('branching_road', {
      name: TEMPLATE_METADATA.branching_road.name,
      size: TEMPLATE_METADATA.branching_road.size,
      layout: [], // Procedurally generated
      parameters: {
        randomWalls: { min: 0, max: 2 },
        extraFloors: { min: 0, max: 3 }
      }
    });

    // Starting Road template - 45x125 map with player starting yard/house at bottom
    this.templates.set('starting_road', {
      name: TEMPLATE_METADATA.starting_road.name,
      size: TEMPLATE_METADATA.starting_road.size,
      layout: [], // Procedurally generated
      parameters: {
        randomWalls: { min: 0, max: 2 },
        extraFloors: { min: 0, max: 3 }
      }
    });

    console.log('[TemplateMapGenerator] Loaded', this.templates.size, 'default templates');
  }

  /**
   * Generate map from template with parameters
   */
  generateFromTemplate(templateName, config = {}) {
    const template = this.templates.get(templateName);
    if (!template) {
      throw new Error(`Template '${templateName}' not found`);
    }

    const builder = new MapBuilder(template.size.width, template.size.height);
    const generator = this.generators.get(templateName);

    if (generator) {
      generator.generate(config, builder);
    } else if (template.layout && template.layout.length > 0) {
      // Legacy support for fixed layout templates
      const parsedLayout = this.parseTemplateLayout(template.layout);
      builder.layout = parsedLayout;
    }

    // Convert builder state to final mapData
    const mapData = builder.getFinalMapData(templateName, config);

    // Apply variations and randomization (only for legacy fixed layouts or specific cases)
    if (!generator && templateName !== 'road') {
      const randomWalls = config.randomWalls || template.parameters?.randomWalls?.min || 0;
      const extraFloors = config.extraFloors || template.parameters?.extraFloors?.min || 0;
      this.addRandomWalls(builder.layout, randomWalls);
      this.addRandomFloors(builder.layout, extraFloors);
      // Re-map tiles after random modifications
      mapData.tiles = this.layoutToTileData(builder.layout);
    }

    // Set transition tiles at road exits. Generators that know their road
    // geometry record exit positions in metadata.exits (the single source of
    // truth); templates without one exit at the horizontal center.
    const centerX = Math.floor(mapData.width / 2);
    const exits = mapData.metadata?.exits;
    const northExitX = exits?.north?.x ?? centerX;
    const southExitX = exits?.south?.x ?? centerX;

    this.setTileData(mapData, northExitX, 0, 'transition');
    if (templateName !== 'starting_road') {
      this.setTileData(mapData, southExitX, mapData.height - 1, 'transition');
    }

    // Add spawn zones metadata
    mapData.metadata.spawnZones = {
      ...template.spawnZones,
      roadStart: [{ x: southExitX, y: mapData.height - 2 }],
      transitionPoints: {
        north: { x: northExitX, y: 0 },
        south: { x: southExitX, y: mapData.height - 1 }
      }
    };

    this.placeWildCrops(mapData);
    this.placeOutdoorDecorations(mapData);
    this.placeIndoorDecorations(mapData);
    this.placeRoadAndSidewalkDecorations(mapData);

    console.log(`[TemplateMapGenerator] Generated '${templateName}' map using ${generator ? 'Strategy' : 'Legacy'} engine`);
    return mapData;
  }

  /**
   * Place wild crops in secluded grass areas
   */
  placeWildCrops(mapData) {
    const validSpots = [];
    const { width, height, tiles } = mapData;

    const compound = mapData.metadata?.townSquareCompound;
    for (let y = 1; y < height - 1; y++) {
      for (let x = 1; x < width - 1; x++) {
        if (isInsideCompound(compound, x, y)) {
          continue;
        }

        const tile = tiles[y][x];
        if (tile.terrain !== 'grass') continue;

        // Check neighbors for seclusion criteria
        let nearBuildingOrWall = false;
        let nearRoadOrSidewalk = false;

        for (let dy = -1; dy <= 1; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            if (dx === 0 && dy === 0) continue;
            const neighbor = tiles[y + dy][x + dx];
            if (!neighbor) continue;

            if (neighbor.terrain === 'building' || neighbor.terrain === 'wall' || neighbor.terrain === 'tent_wall' || neighbor.terrain === 'fence') {
              nearBuildingOrWall = true;
            }
            if (neighbor.terrain === 'road' || neighbor.terrain === 'sidewalk') {
              nearRoadOrSidewalk = true;
            }
          }
        }

        if (nearBuildingOrWall && !nearRoadOrSidewalk) {
          validSpots.push({ x, y });
        }
      }
    }

    if (validSpots.length === 0) return;

    const mapNumber = mapData.config?.mapNumber || 1;
    // If map level > 2, 50% chance that NO wild crops appear (unless it is branching_road)
    const isBranching = mapData.template === 'branching_road';
    if (!isBranching && mapNumber > 2 && gameRandom.next() > 0.5) {
      console.log(`[TemplateMapGenerator] Map ${mapNumber} skipped wild crop generation (50% chance)`);
      return;
    }

    // Pick random spot(s) (1 baseline, 5 on branching_road)
    const count = isBranching ? 5 : 1;
    const selectedSpots = [];
    if (validSpots.length > 0) {
      const shuffledSpots = gameRandom.shuffle([...validSpots]);
      const actualCount = Math.min(count, shuffledSpots.length);
      for (let i = 0; i < actualCount; i++) {
        selectedSpots.push(shuffledSpots[i]);
      }
    }

    // Crop definitions for wild variety
    const crops = [
      { defId: 'provision.harvestable_tomato', name: 'Harvestable Tomato', subtype: 'harvestable_tomato' },
      { defId: 'provision.harvestable_carrot', name: 'Harvestable Carrot', subtype: 'harvestable_carrot' },
      { defId: 'provision.harvestable_corn', name: 'Harvestable Corn', subtype: 'harvestable_corn' }
    ];

    selectedSpots.forEach(spot => {
      const tile = tiles[spot.y][spot.x];
      const cropDef = crops[gameRandom.nextInt(0, crops.length - 1)];

      const wildCropItem = createItemFromDef(cropDef.defId, {
        subtype: cropDef.subtype,
        x: spot.x,
        y: spot.y,
        isWild: true,
        isHarvestable: true
      });

      if (!tile.inventoryItems) tile.inventoryItems = [];
      tile.inventoryItems.push(wildCropItem);
    });

    console.log(`[TemplateMapGenerator] Placed ${selectedSpots.length} wild crops`);
  }

  /**
   * Place outdoor decorations on grass tiles
   */
  placeOutdoorDecorations(mapData) {
    const { width, height, tiles } = mapData;
    const decorTypes = ['outdoordecor1', 'outdoordecor2', 'outdoordecor3', 'outdoordecor4', 'outdoordecor5'];

    const compound = mapData.metadata?.townSquareCompound;
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        if (isInsideCompound(compound, x, y)) {
          continue;
        }

        const tile = tiles[y] && tiles[y][x];
        if (tile && tile.terrain === 'grass') {
          const hasCropsOrItems = tile.inventoryItems && tile.inventoryItems.length > 0;
          if (!hasCropsOrItems && gameRandom.next() < MAP_GEN_CONFIG.decorationProbability) {
            const decor = decorTypes[gameRandom.nextInt(0, decorTypes.length - 1)];
            tile.decoration = decor;
          }
        }
      }
    }
    console.log(`[TemplateMapGenerator] Placed outdoor decorations`);
  }

  /**
   * Place indoor decorations on indoor floor tiles
   */
  placeIndoorDecorations(mapData) {
    const { width, height, tiles } = mapData;
    const decorTypes = ['brokenchair', 'crack', 'debris', 'paper', 'tabledebris'];

    const compound = mapData.metadata?.townSquareCompound;
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        if (isInsideCompound(compound, x, y)) {
          continue;
        }

        const tile = tiles[y] && tiles[y][x];
        if (tile && (tile.terrain === 'floor' || tile.terrain === 'tent_floor')) {
          const hasCropsOrItems = tile.inventoryItems && tile.inventoryItems.length > 0;
          if (!hasCropsOrItems && gameRandom.next() < MAP_GEN_CONFIG.decorationProbability) {
            const decor = decorTypes[gameRandom.nextInt(0, decorTypes.length - 1)];
            tile.decoration = decor;
          }
        }
      }
    }
    console.log(`[TemplateMapGenerator] Placed indoor decorations`);
  }

  /**
   * Place road and sidewalk decorations on road and sidewalk tiles
   */
  placeRoadAndSidewalkDecorations(mapData) {
    const { width, height, tiles } = mapData;
    const decorTypes = ['road1', 'road2', 'road3'];

    const compound = mapData.metadata?.townSquareCompound;
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        if (isInsideCompound(compound, x, y)) {
          continue;
        }

        const tile = tiles[y] && tiles[y][x];
        if (tile && (tile.terrain === 'road' || tile.terrain === 'sidewalk')) {
          const hasCropsOrItems = tile.inventoryItems && tile.inventoryItems.length > 0;
          if (!hasCropsOrItems && gameRandom.next() < MAP_GEN_CONFIG.decorationProbability * 0.5) {
            const decor = decorTypes[gameRandom.nextInt(0, decorTypes.length - 1)];
            tile.decoration = decor;
          }
        }
      }
    }
    console.log(`[TemplateMapGenerator] Placed road and sidewalk decorations`);
  }

  /**
   * Convert layout to tile data format
   */
  layoutToTileData(layout) {
    return layout.map((row, y) =>
      row.map((cell, x) => {
        if (cell && typeof cell === 'object') {
          return {
            x,
            y,
            terrain: cell.terrain,
            edgeWalls: cell.edgeWalls ? { ...cell.edgeWalls } : { n: false, e: false, s: false, w: false },
            contents: [],
            decoration: cell.decoration || null
          };
        }
        return {
          x,
          y,
          terrain: cell,
          edgeWalls: { n: false, e: false, s: false, w: false },
          contents: [],
          decoration: null
        };
      })
    );
  }

  /**
   * Set tile data at specific coordinates
   */
  setTileData(mapData, x, y, terrain) {
    if (y >= 0 && y < mapData.height && x >= 0 && x < mapData.width) {
      // Ensure the row exists
      if (!mapData.tiles[y]) {
        mapData.tiles[y] = [];
      }
      // Ensure the tile data object exists for the coordinate
      if (!mapData.tiles[y][x]) {
        mapData.tiles[y][x] = { x, y, terrain: 'grass', contents: [], decoration: null }; // Default to grass if not initialized
      }
      mapData.tiles[y][x].terrain = terrain;
    }
  }

  /**
   * Parse template layout strings into 2D array
   */
  parseTemplateLayout(layoutStrings) {
    const terrainMap = {
      'w': 'wall',
      'f': 'floor',
      'g': 'grass',
      'r': 'road',
      's': 'sidewalk',
      'F': 'fence',
      'H': 'water',
      '.': 'grass' // Default open space
    };

    return layoutStrings.map(row =>
      row.split('').map(char => terrainMap[char] || 'grass')
    );
  }

  /**
   * Add random walls to layout
   */
  addRandomWalls(layout, count) {
    const height = layout.length;
    const width = layout[0].length;
    let added = 0;
    let attempts = 0;
    const maxAttempts = count * 100;

    while (added < count && attempts < maxAttempts) {
      attempts++;
      const x = Math.floor(gameRandom.next() * width);
      const y = Math.floor(gameRandom.next() * height);

      const cell = layout[y][x];
      const isWall = typeof cell === 'object' ? cell.terrain === 'wall' : cell === 'wall';

      // Don't overwrite existing walls or place on edges
      if (!isWall && x > 0 && x < width - 1 && y > 0 && y < height - 1) {
        if (typeof cell === 'object') {
          cell.terrain = 'wall';
        } else {
          layout[y][x] = 'wall';
        }
        added++;
      }
    }
  }

  /**
   * Add random floor tiles to layout
   */
  addRandomFloors(layout, count) {
    const height = layout.length;
    const width = layout[0].length;
    let added = 0;
    let attempts = 0;
    const maxAttempts = count * 100;

    while (added < count && attempts < maxAttempts) {
      attempts++;
      const x = Math.floor(gameRandom.next() * width);
      const y = Math.floor(gameRandom.next() * height);

      const cell = layout[y][x];
      const isGrass = typeof cell === 'object' ? cell.terrain === 'grass' : cell === 'grass';

      // Only place on grass, not walls or existing floors
      if (isGrass) {
        if (typeof cell === 'object') {
          cell.terrain = 'floor';
        } else {
          layout[y][x] = 'floor';
        }
        added++;
      }
    }
  }

  /**
   * Standardized helper to register building metadata for loot and spawning systems
   */
  _registerBuilding(mapData, type, x, y, width, height, extra = {}) {
    if (!mapData.metadata.buildings) {
      mapData.metadata.buildings = [];
    }

    mapData.metadata.buildings.push({
      type,
      x,
      y,
      width,
      height,
      ...extra
    });

    // Provide backward compatibility for specialBuildings key during map transition phase
    if (isSpecialBuilding(type)) {
      if (!mapData.metadata.specialBuildings) {
        mapData.metadata.specialBuildings = [];
      }
      mapData.metadata.specialBuildings.push(mapData.metadata.buildings[mapData.metadata.buildings.length - 1]);
    }

    console.log(`[TemplateMapGenerator] Registered ${type} building at (${x}, ${y}) size ${width}x${height}`);
  }

  /**
   * Get available templates
   */
  getAvailableTemplates() {
    return Array.from(this.templates.keys()).map(key => ({
      id: key,
      name: this.templates.get(key).name,
      size: this.templates.get(key).size,
      parameters: this.templates.get(key).parameters
    }));
  }

  /**
   * Get template details
   */
  getTemplate(templateName) {
    return this.templates.get(templateName);
  }

  /**
   * Get template-specific starting position
   */
  getStartPosition(templateName = 'road') {
    const template = this.templates.get(templateName);
    const width = template ? template.size.width : 45;
    const height = template ? template.size.height : 125;

    const generator = this.generators.get(templateName);
    if (generator) {
      return generator.getStartPosition(width, height);
    }

    const templateStartPositions = {
      'small_building': { x: 5, y: 7 },
      'mall_section': { x: 7, y: 11 },
      'outdoor_area': { x: 10, y: 19 }
    };

    return templateStartPositions[templateName] || { x: Math.floor(width / 2), y: height - 2 };
  }

  /**
   * Generate a map and apply it to a fresh GameMap, regenerating until it passes
   * the connectivity gate (spawn/exits/buildings reachable). If no attempt fully
   * passes within maxAttempts, the least-bad map is returned with a warning so
   * map generation never deadlocks.
   *
   * @param {string} templateName
   * @param {Object} config - passed to generateFromTemplate (e.g. { mapNumber })
   * @param {Function} GameMapClass - the GameMap constructor (passed in to avoid an import cycle)
   * @param {Object} [opts]
   * @param {number} [opts.maxAttempts=6]
   * @returns {Promise<{ gameMap: Object, mapData: Object, validation: Object, attempts: number }>}
   */
  async generateFromScenario(scenarioData) {
    const { ScenarioMapGenerator } = await import('./generators/ScenarioMapGenerator.js');
    const builder = new MapBuilder(scenarioData.width, scenarioData.height);
    const generator = new ScenarioMapGenerator(scenarioData);
    generator.generate({}, builder);
    const mapData = builder.getFinalMapData('scenario', {});
    mapData.metadata.entities = scenarioData.entities || [];
    mapData.metadata.eventTriggers = scenarioData.eventTriggers || [];
    mapData.metadata.bubbleEvents = scenarioData.bubbleEvents || [];
    // Unified GameEvent model — this is what EventRunner actually reads at
    // runtime (see QUEST_SYSTEM_PLAN.md §6); the legacy arrays above are kept
    // for back-compat with older saved maps.
    mapData.metadata.events = scenarioData.events || [];
    // Switches & Variables registry (editor authoring aid) — read once at map
    // load to seed initial flag/var values (see QuestState.seedFromRegistry).
    mapData.metadata.questRegistry = scenarioData.questRegistry || { flags: [], vars: [] };
    mapData.metadata.entityRegistry = scenarioData.entityRegistry || { entries: [] };
    mapData.metadata.mapTransitions = scenarioData.mapTransitions || [];
    if (scenarioData.metadata?.alwaysDark || scenarioData.alwaysDark) {
      mapData.metadata.alwaysDark = true;
    }
    if (scenarioData.metadata?.spawnZones) {
      mapData.metadata.spawnZones = { ...mapData.metadata.spawnZones, ...scenarioData.metadata.spawnZones };
    }
    return mapData;
  }

  async generateValidatedMap(templateName, config = {}, GameMapClass, { maxAttempts = 6 } = {}) {
    let best = null;
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      const mapData = this.generateFromTemplate(templateName, config);
      const gameMap = new GameMapClass(mapData.width, mapData.height);
      if (config.mapNumber !== undefined) gameMap.mapNumber = config.mapNumber;
      await this.applyToGameMap(gameMap, mapData);

      const validation = validateConnectivity(gameMap, mapData);
      const result = { gameMap, mapData, validation, attempts: attempt };

      if (validation.ok) {
        if (attempt > 1) {
          console.log(`[TemplateMapGenerator] Connectivity OK for '${templateName}' on attempt ${attempt}`);
        }
        return result;
      }

      console.warn(`[TemplateMapGenerator] Connectivity attempt ${attempt}/${maxAttempts} for '${templateName}' failed (score ${validation.score}): ${validation.reasons.join('; ')}`);
      if (!best || validation.score < best.validation.score) best = result;
    }

    console.error(`[TemplateMapGenerator] No fully-connected '${templateName}' map after ${maxAttempts} attempts; using least-bad (score ${best.validation.score})`);
    return best;
  }

  /**
   * Apply template-generated map data to a GameMap instance
   */
  async applyToGameMap(gameMap, templateMapData) {
    try {
      if (!templateMapData || !templateMapData.tiles) {
        throw new Error('Invalid template data: missing tiles array');
      }

      if (templateMapData.template) {
        gameMap.template = templateMapData.template;
      }

      // Verify size compatibility
      if (templateMapData.width !== gameMap.width || templateMapData.height !== gameMap.height) {
        console.warn('[TemplateMapGenerator] Map size mismatch, resizing GameMap');
        gameMap.width = templateMapData.width;
        gameMap.height = templateMapData.height;
        gameMap.initializeMap(); // Reinitialize with new size
      }

      // Apply terrain from template
      for (let y = 0; y < templateMapData.height; y++) {
        for (let x = 0; x < templateMapData.width; x++) {
          if (!templateMapData.tiles[y] || !templateMapData.tiles[y][x]) {
            console.warn(`[TemplateMapGenerator] Missing tile data at (${x}, ${y})`);
            continue;
          }
          const tileData = templateMapData.tiles[y][x];
          if (tileData.terrain) {
            gameMap.setTerrain(x, y, tileData.terrain);
          }

          if (tileData.edgeWalls) {
            const tile = gameMap.getTile(x, y);
            if (tile) {
              tile.edgeWalls = {
                n: !!tileData.edgeWalls.n,
                e: !!tileData.edgeWalls.e,
                s: !!tileData.edgeWalls.s,
                w: !!tileData.edgeWalls.w
              };
            }
          }

          // Transfer inventory items (Wild Crops, etc.)
          if (tileData.inventoryItems && tileData.inventoryItems.length > 0) {
            gameMap.setItemsOnTile(x, y, tileData.inventoryItems);
          }

          // Transfer decoration data
          if (tileData.decoration) {
            const tile = gameMap.getTile(x, y);
            if (tile) {
              tile.decoration = tileData.decoration;
            }
          }
        }
      }

      console.log(`[TemplateMapGenerator] Applied template map data to GameMap (${gameMap.width}x${gameMap.height})`);

      // PHASE 0: CONVERT FULL-TILE WALLS TO EDGE WALLS
      // This allows interior walls to be infinitely thin edge walls, making the space walkable
      const hasDoorOrWindow = (tx, ty) => {
        if (!templateMapData.metadata) return false;
        if (templateMapData.metadata.doors?.some(d => d.x === tx && d.y === ty)) return true;
        if (templateMapData.metadata.windows?.some(w => w.x === tx && w.y === ty)) return true;
        return false;
      };

      for (let y = 0; y < templateMapData.height; y++) {
        for (let x = 0; x < templateMapData.width; x++) {
          const tile = gameMap.getTile(x, y);
          const origTerrain = templateMapData.tiles[y] && templateMapData.tiles[y][x] ? templateMapData.tiles[y][x].terrain : null;

          if (tile && (origTerrain === 'building' || origTerrain === 'wall')) {
            // Check if this tile is on the outer perimeter of a building
            const isOuterWall = templateMapData.metadata?.buildings?.some(b => {
              const isWithinX = x >= b.x && x < b.x + b.width;
              const isWithinY = y >= b.y && y < b.y + b.height;
              if (isWithinX && isWithinY) {
                return x === b.x || x === b.x + b.width - 1 || y === b.y || y === b.y + b.height - 1;
              }
              return false;
            }) || false;

            if (isOuterWall) {
              // Keep outer walls as solid building/wall tiles so they block movement/sight and reveal/render correctly
              continue;
            }

            // Change terrain to floor so the tile is walkable
            gameMap.setTerrain(x, y, 'floor');

            // Check original neighbors to determine which edge walls to create
            const nTile = y > 0 ? templateMapData.tiles[y - 1][x]?.terrain : null;
            const sTile = y < templateMapData.height - 1 ? templateMapData.tiles[y + 1][x]?.terrain : null;
            const wTile = x > 0 ? templateMapData.tiles[y][x - 1]?.terrain : null;
            const eTile = x < templateMapData.width - 1 ? templateMapData.tiles[y][x + 1]?.terrain : null;

            const isWallOrOpening = (t, tx, ty) => t === 'building' || t === 'wall' || hasDoorOrWindow(tx, ty);

            // If a neighboring tile was NOT a wall or door, we need an edge wall separating them
            if (!isWallOrOpening(nTile, x, y - 1)) tile.edgeWalls.n = true;
            if (!isWallOrOpening(sTile, x, y + 1)) tile.edgeWalls.s = true;
            if (!isWallOrOpening(wTile, x - 1, y)) tile.edgeWalls.w = true;
            if (!isWallOrOpening(eTile, x + 1, y)) tile.edgeWalls.e = true;
          }
        }
      }

      // Instantiate door entities from metadata
      if (templateMapData.metadata && templateMapData.metadata.doors) {
        const { Door } = await import('../entities/Door.js');
        templateMapData.metadata.doors.forEach(doorData => {
          const { x, y } = doorData;

          // Phase 2: Create Door entity
          if (!doorData.isOpening) {
            const door = new Door(
              // Include the edge: a corner tile can legitimately host two doors on
              // different edges, which collide if the id is only (x,y).
              doorData.id || `door-${doorData.x}-${doorData.y}-${doorData.edge || 'x'}`,
              doorData.x,
              doorData.y,
              doorData.isLocked,
              doorData.isOpen,
              false,
              doorData.edge
            );
            const registry = templateMapData.metadata?.entityRegistry;
            if (registry?.entries) {
              const match = registry.entries.find(e => e.type === 'door' && e.x === doorData.x && e.y === doorData.y);
              if (match) door.registryTag = match.tag;
            }
            gameMap.addEntity(door, doorData.x, doorData.y);
          } else {
            // It's an open doorway (no physical door), so clear the edge wall!
            const tile = gameMap.getTile(doorData.x, doorData.y);
            if (tile && tile.edgeWalls && doorData.edge) {
              tile.edgeWalls[doorData.edge] = false;
            }
          }

          // Ensure the door site itself is definitely walkable (floor)
          gameMap.setTerrain(doorData.x, doorData.y, 'floor');
        });
        console.log(`[TemplateMapGenerator] Added ${templateMapData.metadata.doors.length} doors`);
      }

      // Instantiate window entities from metadata
      if (templateMapData.metadata && templateMapData.metadata.windows) {
        const { Window } = await import('../entities/Window.js');
        templateMapData.metadata.windows.forEach(windowData => {
          const window = new Window(
            // Include the edge so two windows on different edges of one tile don't collide.
            windowData.id || `window-${windowData.x}-${windowData.y}-${windowData.edge || 'x'}`,
            windowData.x,
            windowData.y,
            windowData.isLocked,
            windowData.isOpen,
            windowData.isBroken,
            windowData.edge
          );
          const registry = templateMapData.metadata?.entityRegistry;
          if (registry?.entries) {
            const match = registry.entries.find(e => e.type === 'window' && e.x === windowData.x && e.y === windowData.y);
            if (match) window.registryTag = match.tag;
          }
          gameMap.addEntity(window, windowData.x, windowData.y);

          // Ensure the window site itself is definitely walkable (floor)
          gameMap.setTerrain(windowData.x, windowData.y, 'floor');
        });
        console.log(`[TemplateMapGenerator] Added ${templateMapData.metadata.windows.length} windows to map`);
      }

      // Instantiate place icons from metadata
      if (templateMapData.metadata && templateMapData.metadata.placeIcons) {
        const { PlaceIcon } = await import('../entities/PlaceIcon.js');
        templateMapData.metadata.placeIcons.forEach(iconData => {
          const icon = new PlaceIcon(
            iconData.id || `icon-${iconData.subtype}-${iconData.x}-${iconData.y}`,
            iconData.x,
            iconData.y,
            iconData.subtype
          );
          if (iconData.subtype === 'fuelpump') {
            icon.blocksMovement = true;
          }
          gameMap.addEntity(icon, iconData.x, iconData.y);
        });
        console.log(`[TemplateMapGenerator] Added ${templateMapData.metadata.placeIcons.length} icons to map`);
      }

      // Store standardized building metadata on gameMap
      if (templateMapData.metadata) {
        gameMap.metadata = templateMapData.metadata;
        if (templateMapData.metadata.buildings) {
          gameMap.buildings = templateMapData.metadata.buildings;
        }
        if (templateMapData.metadata.specialBuildings) {
          gameMap.specialBuildings = templateMapData.metadata.specialBuildings;
        }
        if (templateMapData.metadata.lowSpots) {
          gameMap.lowSpots = templateMapData.metadata.lowSpots;
        }
      }

      // Place placeable.help items on event trigger tiles
      if (templateMapData.metadata?.eventTriggers?.length > 0) {
        const { createItemFromDef } = await import('../inventory/ItemDefs.js');
        const { Item } = await import('../inventory/Item.js');
        for (const trigger of templateMapData.metadata.eventTriggers) {
          const tile = gameMap.getTile(trigger.x, trigger.y);
          if (!tile) continue;
          const alreadyHasHelp = tile.inventoryItems?.some(i => i.defId === 'placeable.help');
          if (!alreadyHasHelp) {
            const helpDef = createItemFromDef('placeable.help');
            if (helpDef) {
              const helpItem = new Item(helpDef);
              helpItem.x = trigger.x;
              helpItem.y = trigger.y;
              if (!tile.inventoryItems) tile.inventoryItems = [];
              tile.inventoryItems.push(helpItem);
              gameMap.setItemsOnTile(trigger.x, trigger.y, tile.inventoryItems);
            }
          }
        }
      }

      // Spawn scenario entities (zombies, NPCs, etc.)
      if (templateMapData.metadata?.entities?.length > 0) {
        const { EntityFactory } = await import('../EntityFactory.js');
        for (const e of templateMapData.metadata.entities) {
            if (e.type === 'player') continue;
            try {
              let entity;
              if (e.type === 'zombie') {
                entity = EntityFactory.createZombie(e.x, e.y, e.subtype || 'basic');
                if (e.hp && entity) {
                  const health = entity.getComponent?.('Health');
                  if (health) { health.current = Math.min(e.hp, health.max); }
                }
                if (e.noLoot && entity) entity.noLoot = true;
                if (e.deaf && entity) entity.deaf = true;

                const registry = templateMapData.metadata?.entityRegistry;
                if (registry?.entries) {
                  const match = registry.entries.find(me => me.type === 'zombie' && me.x === e.x && me.y === e.y);
                  if (match) entity.registryTag = match.tag;
                }
              } else if (e.type === 'npc') {
                // Preserve the authored NPC identity (typeId/subtype, name, hostility)
                // instead of collapsing every scenario NPC to a generic survivor.
                entity = EntityFactory.createNPC(
                  e.x, e.y,
                  e.isHostile || false,
                  e.typeId || e.subtype || 'survivor',
                  e.name || null,
                  null,
                  e.iconId || null
                );
                if (e.aiDisabled && entity) entity.aiDisabled = true;
              }
              if (entity) gameMap.addEntity(entity, e.x, e.y);
          } catch (err) {
            console.warn(`[TemplateMapGenerator] Failed to spawn scenario entity:`, e, err);
          }
        }
        console.log(`[TemplateMapGenerator] Spawned ${templateMapData.metadata.entities.filter(e => e.type !== 'player').length} scenario entities`);
      }

      return gameMap;
    } catch (error) {
      console.error('[TemplateMapGenerator] Failed to apply template to GameMap:', error);
      throw error;
    }
  }
}
